### ISSUE TITLE
Add release

### ISSUE THREAD

**Issue by TKX42** [PhoenixC2/Frontend#3]
The release link of the plugin (https://github/PhoenixC2/PheonixC2-Frontend/releases/latest/download/phoenixc2-dist.zip) doesn't exist.

**Comment by lucahennemann** [comment]
As I stated in the [issue](https://github.com/PhoenixC2/PhoenixC2/issues/50) you opened on the main repository, the frontend is not finished yet. So there is no also no release. The command to add plugins automatically is also not supported in the main branch, because it is a feature of v1.1. The readme instructions of this repo should be usable after the first release👍
